### ISSUE TITLE
Error getting file system

### ISSUE THREAD

**Issue by Galaxtone** [Chocohead/Merger#2]
`java.lang.RuntimeException: Error getting file system
Caused by: java.nio.file.FileSystemAlreadyExistsException`

I believe it's occurring when trying to export a merged jar after a previous merged jar has failed, occurring even if the file is deleted or a different filename is used.
May have to do with a jar file handle remaining open after merging jars fails.

**Comment by Chocohead** [comment]
Full stack trace is going to be helpful over which file system it's having trouble getting

**Comment by Galaxtone** [comment]
@Chocohead Update! It appears that it might occur once after any jar merge regardless of success, and the only solution I've found is to restart matcher and recreate a project.

`java.lang.RuntimeException: Error getting file system
        at net.fabricmc.stitch.merge.JarMerger.getJarFileSystem(JarMerger.java:162)
        at net.fabricmc.stitch.merge.JarMerger.<init>(JarMerger.java:179)
        at com.chocohead.merger.menu.MergedJaringMenu.dumpMergedJar(MergedJaringMenu.java:109)
        at com.chocohead.merger.menu.MergedJaringMenu.lambda$12(MergedJaringMenu.java:92)
        at matcher.gui.Gui$2.call(Gui.java:274)
        at matcher.gui.Gui$2.call(Gui.java:271)
        at javafx.concurrent.Task$TaskCallable.call(Task.java:1425)
        at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
        at java.base/java.lang.Thread.run(Thread.java:830)
Caused by: java.nio.file.FileSystemAlreadyExistsException
        at jdk.zipfs/jdk.nio.zipfs.ZipFileSystemProvider.newFileSystem(ZipFileSystemProvider.java:105)
        at java.base/java.nio.file.FileSystems.newFileSystem(FileSystems.java:335)
        at java.base/java.nio.file.FileSystems.newFileSystem(FileSystems.java:284)
        at net.fabricmc.stitch.merge.JarMerger.getJarFileSystem(JarMerger.java:160)
        ... 10 more`

**Comment by Chocohead** [comment]
Ah I have probably fixed this before (in 36b4672), but that was after the version which was released in releases.
